"""
Service catalog: loads the ArcGIS services CSV and provides lookup functions.

The CSV is generated by `_ingestion.py` and contains pre-parsed metadata
for each ArcGIS FeatureServer service available on the ONS Geoportal.
"""

import csv
import os

ARCGIS_BASE_URL = "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/"
_CSV_PATH = os.path.join(os.path.dirname(__file__), "data", "arcgis_services.csv")


def _load_services() -> list[dict]:
    """Load services from CSV. Called once at module import."""
    with open(_CSV_PATH, encoding="utf-8") as f:
        return list(csv.DictReader(f))


_services: list[dict] = _load_services()


def find_services(
    geography_type: str | None = None,
    year: str | None = None,
    month: str | None = None,
    coverage: str | None = None,
    boundary_type: str | None = None,
) -> list[dict]:
    """Filter services by any combination of criteria."""
    results = _services
    if geography_type:
        results = [s for s in results if s["geography"] == geography_type]
    if year:
        results = [s for s in results if s["year"] == year]
    if month:
        month_upper = month.upper()
        results = [s for s in results if (s.get("month") or "").upper() == month_upper]
    if coverage:
        results = [s for s in results if s["region"] == coverage]
    if boundary_type:
        results = [s for s in results if s["resolution"] == boundary_type]
    return results


def get_most_recent_service(
    geography_type: str,
    coverage: str,
    boundary_type: str | None = None,
) -> str | None:
    """Return the arcgis_id of the most recent matching service."""
    matches = find_services(
        geography_type=geography_type,
        coverage=coverage,
        boundary_type=boundary_type,
    )
    if not matches:
        return None
    matches.sort(
        key=lambda s: int(s["year"]) if s["year"].isdigit() else 0,
        reverse=True,
    )
    return matches[0]["arcgis_id"]


def get_service_url(service_name: str) -> str:
    """Build the FeatureServer URL for a service name."""
    return f"{ARCGIS_BASE_URL}{service_name}/FeatureServer"
