site_name: KindTech

# Repository information
repo_name: KindTechUK/kindtech
repo_url: https://github.com/KindTechUK/kindtech

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # Top navigation bar
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

    # Other features
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.tooltips
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

# Navigation structure
nav:
  - Home: index.md
  - API Reference:
    - Overview: api/index.md
    - Geographic Data: api/geo.md
    - ONS Data: api/ons.md
  - Blog:
    - blog/index.md
