"""
NOMIS dataset catalog: loads the CSV and provides lookup functions.

The CSV is generated by `_ingestion.py` and contains metadata
for each dataset available on the NOMIS API.
"""

import csv
import os

_CSV_PATH = os.path.join(os.path.dirname(__file__), "data", "nomis_tables.csv")


def _load_tables() -> list[dict]:
    """Load NOMIS tables from CSV. Called once at module import."""
    with open(_CSV_PATH, encoding="utf-8") as f:
        return list(csv.DictReader(f))


_tables: list[dict] = _load_tables()


def find_tables(
    name: str | None = None,
    source: str | None = None,
) -> list[dict]:
    """Filter tables by name (substring) or source."""
    results = _tables
    if name:
        name_lower = name.lower()
        results = [t for t in results if name_lower in t["name"].lower()]
    if source:
        source_lower = source.lower()
        results = [
            t for t in results if (t.get("sourceName") or "").lower() == source_lower
        ]
    return results


def is_valid_dataset(dataset_id: str) -> bool:
    """Check if a dataset ID exists in the catalog."""
    return any(t["id"] == dataset_id for t in _tables)
